// 常用国家英文-中文对照表，可直接用于ECharts、表格、数据处理
const countryNameMap = {
  "China": "中国",
  "United States": "美国",
  "United Kingdom": "英国",
  "France": "法国",
  "Germany": "德国",
  "Russia": "俄罗斯",
  "Japan": "日本",
  "South Korea": "韩国",
  "India": "印度",
  "Brazil": "巴西",
  "Canada": "加拿大",
  "Australia": "澳大利亚",
  "Italy": "意大利",
  "Spain": "西班牙",
  "Mexico": "墨西哥",
  "Turkey": "土耳其",
  "Indonesia": "印度尼西亚",
  "Saudi Arabia": "沙特阿拉伯",
  "South Africa": "南非",
  "Argentina": "阿根廷",
  "Egypt": "埃及",
  "Vietnam": "越南",
  "Thailand": "泰国",
  "Malaysia": "马来西亚",
  "Singapore": "新加坡",
  "Philippines": "菲律宾",
  "Pakistan": "巴基斯坦",
  "Bangladesh": "孟加拉国",
  "Ukraine": "乌克兰",
  "Poland": "波兰",
  "Netherlands": "荷兰",
  "Sweden": "瑞典",
  "Norway": "挪威",
  "Finland": "芬兰",
  "Denmark": "丹麦",
  "Switzerland": "瑞士",
  "Austria": "奥地利",
  "Belgium": "比利时",
  "Greece": "希腊",
  "Portugal": "葡萄牙",
  "Czechia": "捷克",
  "Hungary": "匈牙利",
  "Romania": "罗马尼亚",
  "Chile": "智利",
  "Colombia": "哥伦比亚",
  "Peru": "秘鲁",
  "New Zealand": "新西兰",
  "Ireland": "爱尔兰",
  "Israel": "以色列",
  "United Arab Emirates": "阿联酋",
  "Qatar": "卡塔尔",
  "Kuwait": "科威特",
  "Morocco": "摩洛哥",
  "Nigeria": "尼日利亚",
  "Kenya": "肯尼亚",
  "Ethiopia": "埃塞俄比亚",
  "Algeria": "阿尔及利亚",
  "Venezuela": "委内瑞拉",
  "Cuba": "古巴",
  "North Korea": "朝鲜",
  "Hong Kong": "中国香港",
  "Taiwan": "中国台湾",
  "Macau": "中国澳门"
  // ...如需更多可补充...
};
